"""
Lee's Road Assist — Safenet WABA Webhook Server
================================================
Standalone FastAPI webhook for Safenet WhatsApp Business API.
Handles the Meta-standard webhook protocol (same format Safenet uses).

Flows:
  greeting      → shows service menu (interactive list)
  choose_service → captures service type
  location      → captures location text / coordinates
  confirm       → creates service request + sends confirmation

Run:  uvicorn whatsapp_webhook:app --port 8001 --reload
Expose: cloudflared tunnel --url http://localhost:8001
Webhook URL: https://<generated>.trycloudflare.com/webhook
Verify token: from WHATSAPP_VERIFY_TOKEN env var
"""

import os
import base64
import hmac
import hashlib
import logging
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import httpx
from fastapi import FastAPI, Request, Response, HTTPException, status

# Crypto imports for WABA Flow endpoint E2E encryption
try:
    from cryptography.hazmat.primitives.asymmetric import padding as _asym_padding
    from cryptography.hazmat.primitives import hashes as _hashes, serialization as _serialization
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    from cryptography.hazmat.backends import default_backend as _default_backend
    _CRYPTO_AVAILABLE = True
except ImportError:
    _CRYPTO_AVAILABLE = False

# Load .env from the directory containing this file so the bot always has
# credentials regardless of how uvicorn is launched.
try:
    from dotenv import load_dotenv          # type: ignore
    _env_file = Path(__file__).parent / ".env"
    if _env_file.exists():
        load_dotenv(_env_file, override=False)  # don't override values already in env
except ImportError:
    pass  # python-dotenv not installed; rely on OS environment

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("whatsapp_bot")

# ─── Config (override via environment variables or .env) ──────────────────────
VERIFY_TOKEN      = os.getenv("WHATSAPP_VERIFY_TOKEN",    "WL7LELgtIm20L3ZeflNA7kOF4f74zM6E")
APP_SECRET        = os.getenv("WHATSAPP_APP_SECRET",      "")          # optional — for payload signature
ACCESS_TOKEN      = os.getenv("WHATSAPP_ACCESS_TOKEN",    "")          # Meta bearer token
PHONE_NUMBER_ID   = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "849263908263815")
GRAPH_URL         = os.getenv("WHATSAPP_GRAPH_URL",       "https://graph.facebook.com/v21.0")
BACKEND_API       = os.getenv("BACKEND_API_URL",          "http://localhost:8000/api/v1")
BACKEND_API_KEY   = os.getenv("BACKEND_API_KEY",          "")          # optional internal key
# WABA Flow IDs — set after uploading flows via scripts/upload_flows.py
CUSTOMER_FLOW_ID  = os.getenv("WHATSAPP_CUSTOMER_FLOW_ID", "")  # Fill after upload
PROVIDER_FLOW_ID  = os.getenv("WHATSAPP_PROVIDER_FLOW_ID", "")  # Fill after upload
FLOW_ENDPOINT_URL = os.getenv("WHATSAPP_FLOW_ENDPOINT_URL", "")  # Public URL of this server's /flow-endpoint
WABA_ID           = os.getenv("WHATSAPP_WABA_ID",          "")   # Your WABA / Business Account ID
# Path to the RSA private key generated by scripts/upload_flows.py
FLOW_PRIVATE_KEY_PATH = os.getenv(
    "WHATSAPP_FLOW_PRIVATE_KEY_PATH",
    str(Path(__file__).parent / "whatsapp_flows" / "flows_private_key.pem"),
)

# Load RSA private key for Flow endpoint decryption (loaded once at startup)
_FLOW_PRIVATE_KEY = None
if _CRYPTO_AVAILABLE:
    _key_path = Path(FLOW_PRIVATE_KEY_PATH)
    if _key_path.exists():
        try:
            _FLOW_PRIVATE_KEY = _serialization.load_pem_private_key(
                _key_path.read_bytes(), password=None, backend=_default_backend()
            )
            logger.info("Flow RSA private key loaded from %s", _key_path)
        except Exception as _e:
            logger.warning("Could not load Flow RSA key: %s", _e)
    else:
        logger.warning("Flow RSA key not found at %s — /flow-endpoint will reject encrypted requests", _key_path)

# In-memory conversation state (restarts on server restart; use Redis for prod)
# Key: phone  →  {"flow": str, "data": dict, "updated_at": str}
_sessions: dict[str, dict] = {}

app = FastAPI(title="Lee's Road Assist — WhatsApp Bot", docs_url="/docs")


# ─── Utility: send a WhatsApp message ─────────────────────────────────────────

async def wa_send(to: str, payload: dict) -> dict:
    """POST a message payload to Meta Graph API."""
    url = f"{GRAPH_URL}/{PHONE_NUMBER_ID}/messages"
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            url,
            headers={
                "Authorization": f"Bearer {ACCESS_TOKEN}",
                "Content-Type": "application/json",
            },
            json={"messaging_product": "whatsapp", "to": to, **payload},
        )
        if resp.status_code >= 400:
            logger.error(f"WA send error {resp.status_code}: {resp.text[:300]}")
        return resp.json()


async def wa_text(to: str, body: str) -> None:
    await wa_send(to, {"type": "text", "text": {"body": body, "preview_url": False}})


async def wa_interactive_list(to: str, header: str, body: str, button: str, sections: list) -> None:
    await wa_send(to, {
        "type": "interactive",
        "interactive": {
            "type": "list",
            "header": {"type": "text", "text": header},
            "body": {"text": body},
            "action": {"button": button, "sections": sections},
        },
    })


async def wa_interactive_buttons(to: str, body: str, buttons: list[tuple[str, str]]) -> None:
    """buttons: list of (id, label) tuples — max 3."""
    await wa_send(to, {
        "type": "interactive",
        "interactive": {
            "type": "button",
            "body": {"text": body},
            "action": {
                "buttons": [
                    {"type": "reply", "reply": {"id": bid, "title": label}}
                    for bid, label in buttons[:3]
                ]
            },
        },
    })


async def wa_flow(
    to: str,
    flow_id: str,
    flow_cta: str,
    header: str,
    body: str,
    init_screen: str = "SERVICE_SELECT",
    flow_data: Optional[dict] = None,
    footer: str = "Lee's Road Assist — 24/7",
) -> str:
    """
    Send a WhatsApp Flow message.
    Returns the flow_token (UUID) so it can be stored for correlation.
    Requires ACCESS_TOKEN and PHONE_NUMBER_ID to be set.
    """
    token = str(uuid.uuid4())
    action_payload: dict = {"screen": init_screen}
    if flow_data:
        action_payload["data"] = flow_data
    params: dict = {
        "flow_message_version": "3",
        "flow_token": token,
        "flow_id": flow_id,
        "flow_cta": flow_cta,
        "flow_action": "navigate",
        "flow_action_payload": action_payload,
    }
    # v6.1 flows use only navigate/complete — no endpoint needed.
    # Do NOT include flow_endpoint; it would trigger Meta's health check.
    await wa_send(to, {
        "type": "interactive",
        "interactive": {
            "type": "flow",
            "header": {"type": "text", "text": header},
            "body": {"text": body},
            "footer": {"text": footer},
            "action": {
                "name": "flow",
                "parameters": params,
            },
        },
    })
    return token


# ─── Session helpers ──────────────────────────────────────────────────────────

def get_session(phone: str) -> dict:
    return _sessions.get(phone, {"flow": "greeting", "data": {}})


def set_session(phone: str, flow: str, data: Optional[dict] = None) -> None:
    _sessions[phone] = {
        "flow": flow,
        "data": data or _sessions.get(phone, {}).get("data", {}),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }


def update_data(phone: str, **kwargs) -> None:
    session = get_session(phone)
    session["data"].update(kwargs)
    _sessions[phone] = session


def reset_session(phone: str) -> None:
    _sessions.pop(phone, None)


# ─── Service menu ─────────────────────────────────────────────────────────────

SERVICE_SECTIONS = [
    {
        "title": "Mechanical",
        "rows": [
            {"id": "battery",  "title": "Battery Jump Start",  "description": "Dead battery — quick jump start"},
            {"id": "tyre",     "title": "Tyre Change",         "description": "Flat tyre — on-site swap"},
            {"id": "fuel",     "title": "Fuel Delivery",       "description": "Out of fuel — we deliver"},
            {"id": "lockout",  "title": "Lockout Rescue",       "description": "Locked out of your vehicle"},
            {"id": "repair",   "title": "On-Site Repair",       "description": "Minor mechanical issues"},
        ],
    },
    {
        "title": "Towing",
        "rows": [
            {"id": "tow_local",    "title": "Local Tow",       "description": "Tow within the city"},
            {"id": "tow_long",     "title": "Long Distance Tow","description": "Inter-city towing"},
        ],
    },
    {
        "title": "Emergency",
        "rows": [
            {"id": "accident",  "title": "Accident Assistance", "description": "Accident scene — we help"},
            {"id": "other",     "title": "Other Issue",          "description": "Something else"},
        ],
    },
]

SERVICE_LABELS = {
    "battery":   "Battery Jump Start",
    "tyre":      "Tyre Change",
    "fuel":      "Fuel Delivery",
    "lockout":   "Lockout Rescue",
    "repair":    "On-Site Repair",
    "tow_local": "Local Tow",
    "tow_long":  "Long Distance Tow",
    "accident":  "Accident Assistance",
    "other":     "Other Issue",
}


# ─── Bot conversation logic ───────────────────────────────────────────────────

async def handle_message(phone: str, text: str, msg_type: str, raw_msg: dict) -> None:
    """
    Drive the conversation state machine.
    Each function corresponds to a flow stage.
    """
    session = get_session(phone)
    flow = session["flow"]

    # ── WABA Flow completion (nfm_reply) ──────────────────────────────────────
    # This fires when the user submits a WhatsApp Flow form.
    if msg_type == "interactive":
        interactive = raw_msg.get("interactive", {})
        if interactive.get("type") == "nfm_reply":
            nfm = interactive.get("nfm_reply", {})
            try:
                flow_data = json.loads(nfm.get("response_json", "{}"))
            except json.JSONDecodeError:
                flow_data = {}
            logger.info(f"[{phone}] nfm_reply received: {json.dumps(flow_data)[:200]}")
            # Route based on current session flow
            if flow in ("flow_provider_pending",) or flow_data.get("assignment_id"):
                await handle_provider_flow_reply(phone, flow_data)
            else:
                await handle_customer_flow_reply(phone, flow_data)
            return

    # Make input handling case-insensitive; trim whitespace
    text_lower = (text or "").strip().lower()

    logger.info(f"[{phone}] flow={flow} | msg='{text[:60] if text else '<empty>'}'")

    # Global escape: "menu", "hi", "hello", "restart" always restarts
    if text_lower in ("menu", "hi", "hello", "restart", "start", "0") and flow not in ("greeting",):
        reset_session(phone)
        flow = "greeting"

    # ── GREETING ──────────────────────────────────────────────────────────────
    if flow == "greeting":
        if CUSTOMER_FLOW_ID:
            # Send the interactive Flow (native WhatsApp form UI)
            set_session(phone, "flow_customer_pending")
            await wa_text(phone,
                "👋 Welcome to *Lee's Road Assist* — Zimbabwe's #1 roadside assistance service!\n\n"
                "We're available *24/7* across Harare, Bulawayo, and major routes.\n\n"
                "Tap the button below to request help ⤵️"
            )
            await wa_flow(
                phone,
                flow_id=CUSTOMER_FLOW_ID,
                flow_cta="Request Assistance",
                header="Lee's Road Assist",
                body="Fill in the short form and we'll dispatch the nearest certified technician to you.",
                init_screen="SERVICE_SELECT",
            )
        else:
            # Fallback: text-based conversation (no Flow ID configured yet)
            set_session(phone, "choose_service")
            await wa_text(phone,
                "👋 Welcome to *Lee's Road Assist* — Zimbabwe's #1 roadside assistance service!\n\n"
                "We're available *24/7* across Harare, Bulawayo, and major routes.\n\n"
                "How can we help you today?"
            )
            await wa_interactive_list(
                phone,
                header="Lee's Road Assist",
                body="Select the service you need and we'll dispatch a technician to your location.",
                button="View Services",
                sections=SERVICE_SECTIONS,
            )
        return

    # ── CHOOSE SERVICE ────────────────────────────────────────────────────────
    if flow == "choose_service":
        # Interactive list reply comes as interactive.list_reply.id
        service_id = None
        if msg_type == "interactive":
            interactive = raw_msg.get("interactive", {})
            reply = interactive.get("list_reply") or interactive.get("button_reply") or {}
            service_id = reply.get("id")
        elif text_lower in SERVICE_LABELS:
            service_id = text_lower

        if not service_id or service_id not in SERVICE_LABELS:
            await wa_text(phone,
                "Please tap *View Services* above to choose a service, or type *menu* to start over."
            )
            return

        update_data(phone, service=service_id, service_label=SERVICE_LABELS[service_id])
        set_session(phone, "collect_location", _sessions[phone]["data"])

        await wa_text(phone,
            f"Got it — *{SERVICE_LABELS[service_id]}* 👍\n\n"
            "📍 Please share your *location*:\n"
            "• Tap the 📎 attachment icon → *Location* to share GPS coordinates, OR\n"
            "• Type your address/area (e.g. _Avondale, Harare_ or _Corner 1st & Main_)"
        )
        return

    # ── COLLECT LOCATION ──────────────────────────────────────────────────────
    if flow == "collect_location":
        location_text = None

        if msg_type == "location":
            loc = raw_msg.get("location", {})
            lat = loc.get("latitude")
            lng = loc.get("longitude")
            name = loc.get("name", "")
            address = loc.get("address", "")
            location_text = f"{name or ''} {address or ''} (GPS: {lat},{lng})".strip()
        elif text and len(text.strip()) >= 5:
            location_text = text.strip()

        if not location_text:
            await wa_text(phone,
                "We need your location to dispatch a technician.\n"
                "Please share your GPS via the attachment icon, or type your area/address."
            )
            return

        update_data(phone, location=location_text)
        set_session(phone, "collect_description", _sessions[phone]["data"])

        await wa_interactive_buttons(
            phone,
            body=(
                f"📍 Location captured: _{location_text}_\n\n"
                "Is there anything specific we should know? (vehicle make/model, problem details)\n\n"
                "Or tap *Skip* to proceed straight to confirmation."
            ),
            buttons=[("skip_desc", "Skip"), ("add_desc", "Add Details")],
        )
        return

    # ── COLLECT DESCRIPTION (optional) ───────────────────────────────────────
    if flow == "collect_description":
        skip = False
        description = None

        if msg_type == "interactive":
            interactive = raw_msg.get("interactive", {})
            reply = interactive.get("button_reply") or {}
            if reply.get("id") == "skip_desc":
                skip = True
            elif reply.get("id") == "add_desc":
                set_session(phone, "collect_description_text", _sessions[phone]["data"])
                await wa_text(phone,
                    "Please type your vehicle/issue details (e.g. _Toyota Corolla 2018, won't start_):"
                )
                return
        elif text:
            description = text.strip()

        if not skip and not description:
            # They tapped "Add Details" last time — now collecting the text
            description = text.strip() if text else None

        update_data(phone, description=description or "")
        set_session(phone, "confirm", _sessions[phone]["data"])
        await send_confirmation_prompt(phone)
        return

    # ── COLLECT DESCRIPTION TEXT ──────────────────────────────────────────────
    if flow == "collect_description_text":
        description = text.strip() if text else ""
        update_data(phone, description=description)
        set_session(phone, "confirm", _sessions[phone]["data"])
        await send_confirmation_prompt(phone)
        return

    # ── CONFIRM ───────────────────────────────────────────────────────────────
    if flow == "confirm":
        reply_id = None
        if msg_type == "interactive":
            interactive = raw_msg.get("interactive", {})
            reply = interactive.get("button_reply") or {}
            reply_id = reply.get("id")
        elif text_lower in ("yes", "confirm", "ok", "yep", "sure"):
            reply_id = "confirm_yes"
        elif text_lower in ("no", "cancel", "back"):
            reply_id = "confirm_no"

        if reply_id == "confirm_yes":
            await create_request_and_confirm(phone)
        elif reply_id == "confirm_no":
            reset_session(phone)
            set_session(phone, "choose_service")
            await wa_interactive_list(
                phone,
                header="Lee's Road Assist",
                body="No problem! What service do you need?",
                button="View Services",
                sections=SERVICE_SECTIONS,
            )
        else:
            await send_confirmation_prompt(phone)
        return

    # ── CHOOSE PAYMENT METHOD ─────────────────────────────────────────────────
    if flow == "choose_payment":
        reply_id = None
        if msg_type == "interactive":
            interactive = raw_msg.get("interactive", {})
            reply = interactive.get("list_reply") or interactive.get("button_reply") or {}
            reply_id = reply.get("id")
        elif text_lower in ("cash", "ecocash", "innbucks", "onemoney"):
            reply_id = text_lower

        if reply_id in ("pay_cash", "cash"):
            update_data(phone, payment_method="cash")
            await finalize_payment(phone, "cash")
        elif reply_id in ("pay_ecocash", "ecocash"):
            update_data(phone, payment_method="ecocash")
            set_session(phone, "collect_payment_phone", get_session(phone)["data"])
            await wa_text(phone,
                "📱 *EcoCash Payment*\n\n"
                "Please enter your EcoCash mobile number:\n"
                "(e.g. 0771 234 567 or +263771234567)"
            )
        elif reply_id in ("pay_innbucks", "innbucks"):
            update_data(phone, payment_method="innbucks")
            set_session(phone, "collect_payment_phone", get_session(phone)["data"])
            await wa_text(phone,
                "📱 *InnBucks Payment*\n\n"
                "Please enter your InnBucks mobile number:\n"
                "(e.g. 0771 234 567 or +263771234567)"
            )
        elif reply_id in ("pay_onemoney", "onemoney"):
            update_data(phone, payment_method="onemoney")
            set_session(phone, "collect_payment_phone", get_session(phone)["data"])
            await wa_text(phone,
                "📱 *OneMoney Payment*\n\n"
                "Please enter your OneMoney mobile number:\n"
                "(e.g. 0771 234 567 or +263771234567)"
            )
        else:
            await send_payment_choice_prompt(phone)
        return

    # ── COLLECT PAYMENT PHONE ─────────────────────────────────────────────────
    if flow == "collect_payment_phone":
        if not text or len(text.strip()) < 7:
            await wa_text(phone, "Please enter a valid mobile number (at least 7 digits).")
            return
        update_data(phone, payment_phone=text.strip())
        await finalize_payment(phone, get_session(phone)["data"].get("payment_method", "cash"))
        return

    # ── WAITING / ACTIVE REQUEST ──────────────────────────────────────────────
    if flow in ("waiting", "active"):
        await wa_text(phone,
            "Your request is already active and a technician has been assigned. 🚘\n\n"
            "Type *menu* to start a new request or call *+263 8612 166749* for urgent assistance."
        )
        return
    reset_session(phone)
    await wa_text(phone, "Type *hi* or *menu* to start a new request. 👋")


async def send_confirmation_prompt(phone: str) -> None:
    data = get_session(phone)["data"]
    service_label = data.get("service_label", "Unknown")
    service_id    = data.get("service", "other")
    location      = data.get("location", "Not provided")
    description   = data.get("description", "")

    BACKEND_SERVICE_MAP = {
        "battery":   "battery_jumpstart",
        "tyre":      "tyre_change",
        "fuel":      "fuel_delivery",
        "lockout":   "lockout_rescue",
        "repair":    "onsite_repair",
        "tow_local": "towing",
        "tow_long":  "towing",
        "accident":  "accident_assistance",
        "other":     "other",
    }
    service_slug = BACKEND_SERVICE_MAP.get(service_id, "other")

    # Fetch live price estimate
    price_line = ""
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            headers = {"Content-Type": "application/json"}
            if BACKEND_API_KEY:
                headers["X-Internal-Key"] = BACKEND_API_KEY
            pr = await client.post(
                f"{BACKEND_API}/services/pricing/estimate",
                headers=headers,
                json={
                    "service_type_code": service_slug,
                    "pickup_latitude": -17.8292,
                    "pickup_longitude": 31.0522,
                },
            )
            if pr.status_code == 200:
                p = pr.json()
                price_line = (
                    f"\n💰 *Estimated Cost*\n"
                    f"   🔧 Service fee: ${p.get('service_fee', 5):.2f}\n"
                    f"   📍 Callout fee: ${p.get('callout_fee', 5):.2f}\n"
                )
                if p.get("towing_cost", 0) > 0:
                    price_line += f"   🚛 Towing: ${p.get('towing_cost'):.2f}\n"
                price_line += f"   💵 *Total: ${p.get('total'):.2f} USD*\n"
    except Exception:
        pass

    summary = (
        f"📋 *Request Summary*\n\n"
        f"🔧 Service: *{service_label}*\n"
        f"📍 Location: {location}\n"
    )
    if description:
        summary += f"📝 Details: {description}\n"
    if price_line:
        summary += price_line
    summary += "\nShall we dispatch a technician to you now?\n_(You'll choose payment method next)_"

    await wa_interactive_buttons(
        phone,
        body=summary,
        buttons=[("confirm_yes", "✅ Yes, dispatch!"), ("confirm_no", "❌ Cancel")],
    )


async def create_request_and_confirm(phone: str) -> None:
    """Create service request via backend API, then route to payment step."""
    data = get_session(phone)["data"]
    service_id     = data.get("service")
    service_label  = data.get("service_label", "Roadside Assistance")
    location       = data.get("location", "")
    description    = data.get("description", "")
    payment_method = data.get("payment_method", "cash").lower()

    request_uuid = None
    request_id   = None
    estimated_total: float | None = None
    request_error = None

    # Map our service IDs to backend service type codes
    BACKEND_SERVICE_MAP = {
        "battery":   "battery_jumpstart",
        "tyre":      "tyre_change",
        "fuel":      "fuel_delivery",
        "lockout":   "lockout_rescue",
        "repair":    "onsite_repair",
        "tow_local": "towing",
        "tow_long":  "towing",
        "accident":  "accident_assistance",
        "other":     "other",
    }

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            headers = {"Content-Type": "application/json"}
            if BACKEND_API_KEY:
                headers["X-Internal-Key"] = BACKEND_API_KEY

            resp = await client.post(
                f"{BACKEND_API}/requests/whatsapp",
                headers=headers,
                json={
                    "phone": phone,
                    "service_slug": BACKEND_SERVICE_MAP.get(service_id, "other"),
                    "pickup_address": location,
                    "issue_description": f"{description} [via WhatsApp]".strip(),
                    "channel": "whatsapp",
                    "payment_method": payment_method,
                },
            )
            if resp.status_code in (200, 201):
                rdata = resp.json()
                request_uuid = rdata.get("uuid") or rdata.get("id")
                request_id   = rdata.get("id")
                estimated_total = rdata.get("estimated_price")
            else:
                request_error = resp.text[:200]
                logger.error(f"Backend request creation failed {resp.status_code}: {request_error}")
    except Exception as e:
        request_error = str(e)
        logger.error(f"Backend API error: {e}")

    if request_uuid:
        # Store request details and route to payment
        update_data(phone,
            request_uuid=str(request_uuid),
            request_id=str(request_id) if request_id else None,
            estimated_total=float(estimated_total) if estimated_total else None,
        )
        set_session(phone, "choose_payment", get_session(phone)["data"])
        await send_payment_choice_prompt(phone)
    else:
        # Backend unavailable — still acknowledge and log manually
        set_session(phone, "waiting")
        await wa_text(phone,
            f"✅ *Request Received!*\n\n"
            f"🔧 {service_label}\n"
            f"📍 {location}\n\n"
            f"Our team has been notified and will contact you shortly.\n"
            f"For urgent assistance call *+263 8612 166749*.\n\n"
            f"Type *menu* to start a new request."
        )
        logger.warning(f"Request not saved to backend (phone={phone}): {request_error}")


async def send_payment_choice_prompt(phone: str) -> None:
    """Ask the customer how they want to pay the callout fee."""
    data = get_session(phone)["data"]
    estimated_total = data.get("estimated_total")
    service_label   = data.get("service_label", "Roadside Assistance")
    request_uuid    = data.get("request_uuid", "")

    price_note = f"*${estimated_total:.2f} USD*" if estimated_total else "to be confirmed"

    await wa_interactive_list(
        phone,
        header="💳 Pay Callout Fee",
        body=(
            f"✅ Request created for *{service_label}*!\n\n"
            f"Estimated total: {price_note}\n\n"
            f"Please choose your preferred payment method to confirm your booking. "
            f"The callout fee secures your technician dispatch."
        ),
        button="Choose Payment",
        sections=[
            {
                "title": "Mobile Money",
                "rows": [
                    {"id": "pay_ecocash",  "title": "EcoCash",   "description": "USSD push to your EcoCash number"},
                    {"id": "pay_innbucks", "title": "InnBucks",  "description": "USSD push to your InnBucks number"},
                    {"id": "pay_onemoney", "title": "OneMoney",  "description": "USSD push to your OneMoney number"},
                ],
            },
            {
                "title": "Other",
                "rows": [
                    {"id": "pay_cash", "title": "Cash on Arrival", "description": "Pay the technician when they arrive"},
                ],
            },
        ],
    )


async def finalize_payment(phone: str, payment_method: str) -> None:
    """Initiate payment via backend and send confirmation to user."""
    data = get_session(phone)["data"]
    request_uuid   = data.get("request_uuid", "")
    service_label  = data.get("service_label", "Roadside Assistance")
    location       = data.get("location", "")
    estimated_total = data.get("estimated_total")
    payment_phone  = data.get("payment_phone", phone)

    set_session(phone, "waiting")

    # Call the backend internal payment endpoint
    payment_result = None
    if request_uuid:
        try:
            async with httpx.AsyncClient(timeout=20) as client:
                headers = {"Content-Type": "application/json"}
                if BACKEND_API_KEY:
                    headers["X-Internal-Key"] = BACKEND_API_KEY
                pr = await client.post(
                    f"{BACKEND_API}/payments/whatsapp-init",
                    headers=headers,
                    json={
                        "request_uuid": request_uuid,
                        "payment_provider": payment_method,
                        "phone_number": payment_phone if payment_method != "cash" else "",
                        "amount": float(estimated_total) if estimated_total else None,
                        "currency": "USD",
                    },
                )
                if pr.status_code in (200, 201):
                    payment_result = pr.json()
                else:
                    logger.warning(f"Payment init status {pr.status_code}: {pr.text[:200]}")
        except Exception as pe:
            logger.warning(f"Payment init failed: {pe}")

    # Build confirmation message
    payment_labels = {
        "cash": "Cash on Arrival 💵",
        "ecocash":  "EcoCash 📱",
        "innbucks": "InnBucks 💳",
        "onemoney": "OneMoney 💳",
    }
    label = payment_labels.get(payment_method, payment_method)
    price_note = f"\n💵 *Total: ${estimated_total:.2f} USD*\n" if estimated_total else "\n"

    if payment_method == "cash":
        await wa_text(phone,
            f"✅ *Booking Confirmed — Cash on Arrival!*\n\n"
            f"🔧 {service_label}\n"
            f"📍 {location}\n"
            f"{price_note}"
            f"💳 Payment: {label}\n\n"
            f"🚗 We're dispatching the nearest technician to you now.\n"
            f"📱 You'll receive updates here on WhatsApp.\n"
            f"🆔 Ref: *{request_uuid}*\n\n"
            f"For urgent help call *+263 8612 166749*.\n"
            f"Type *menu* to start a new request."
        )
    elif payment_result and payment_result.get("ok"):
        redirect_url = payment_result.get("redirect_url")
        if redirect_url:
            await wa_text(phone,
                f"✅ *Payment Link Ready!*\n\n"
                f"🔧 {service_label}\n"
                f"{price_note}"
                f"💳 Payment: {label}\n\n"
                f"👆 *Tap the link below to complete your {label} payment:*\n"
                f"{redirect_url}\n\n"
                f"Once payment is confirmed your technician will be dispatched.\n"
                f"🆔 Ref: *{request_uuid}*\n\n"
                f"Type *menu* anytime or call *+263 8612 166749* for support."
            )
        else:
            await wa_text(phone,
                f"✅ *USSD Push Sent!*\n\n"
                f"🔧 {service_label}\n"
                f"{price_note}"
                f"💳 Payment: {label}\n\n"
                f"📲 *Check your phone* — you should receive a {label} USSD prompt shortly.\n"
                f"Approve the payment to confirm your technician dispatch.\n\n"
                f"🆔 Ref: *{request_uuid}*\n\n"
                f"Problems? Call *+263 8612 166749* or type *menu*."
            )
    else:
        # Payment init failed — still acknowledge booking
        error_note = payment_result.get("error", "payment gateway unavailable") if payment_result else "could not reach payment gateway"
        await wa_text(phone,
            f"✅ *Request Confirmed!*\n\n"
            f"🔧 {service_label}\n"
            f"📍 {location}\n"
            f"{price_note}"
            f"💳 Requested: {label}\n\n"
            f"⚠️ We couldn't initiate online payment right now ({error_note}).\n"
            f"Our team will contact you shortly to arrange payment.\n\n"
            f"🆔 Ref: *{request_uuid}*\n"
            f"📞 Urgent? Call *+263 8612 166749*.\n\n"
            f"Type *menu* to start a new request."
        )


# ─── WABA Flow completion handlers ───────────────────────────────────────────

async def handle_customer_flow_reply(phone: str, data: dict) -> None:
    """
    Called when a customer completes the customer_request_flow (nfm_reply).
    Builds request data from the flow payload and creates the service request.
    """
    service_type = data.get("service_type", "other")
    address      = data.get("address", "")
    landmark     = data.get("landmark", "")
    description  = data.get("description", "")
    vehicle_make  = data.get("vehicle_make", "")
    vehicle_model = data.get("vehicle_model", "")
    vehicle_year  = str(data.get("vehicle_year", "")).strip()
    vehicle_color = data.get("vehicle_color", "")
    payment_method = data.get("payment_method", "cash")

    service_label = SERVICE_LABELS.get(service_type, "Roadside Assistance")

    # Build a clean location string
    location_parts = [address]
    if landmark:
        location_parts.append(f"near {landmark}")
    location = ", ".join(p for p in location_parts if p)

    # Build vehicle info string for the description
    vehicle_parts = [vehicle_color, vehicle_make, vehicle_model, vehicle_year]
    vehicle_info = " ".join(p for p in vehicle_parts if p)
    if vehicle_info:
        full_description = f"{description} | Vehicle: {vehicle_info}".strip(" |")
    else:
        full_description = description

    # Store in session so create_request_and_confirm() can read it
    update_data(
        phone,
        service=service_type,
        service_label=service_label,
        location=location,
        description=full_description,
        payment_method="cash",  # default; overridden by payment step
    )
    # Move to confirm flow so the customer sees pricing + can confirm/cancel
    set_session(phone, "confirm", get_session(phone)["data"])
    await send_confirmation_prompt(phone)


async def handle_provider_flow_reply(phone: str, data: dict) -> None:
    """
    Called when a provider responds to the provider_job_flow (nfm_reply).
    Accepts or declines the job via the backend API.
    """
    assignment_id = data.get("assignment_id")
    request_uuid  = data.get("request_uuid", "")
    response      = data.get("response", "")
    eta_minutes   = str(data.get("eta_minutes", "")).strip()

    if not assignment_id:
        await wa_text(phone, "⚠️ Could not process your response — missing job ID. Please call dispatch.")
        return

    if response == "accept":
        try:
            async with httpx.AsyncClient(timeout=15) as client:
                headers = {"Content-Type": "application/json"}
                if BACKEND_API_KEY:
                    headers["X-Internal-Key"] = BACKEND_API_KEY
                resp = await client.post(
                    f"{BACKEND_API}/providers/jobs/{assignment_id}/start",
                    headers=headers,
                )
            if resp.status_code in (200, 201):
                eta_note = f"\n⏱️ ETA you gave: *{eta_minutes} minutes*" if eta_minutes else ""
                await wa_text(phone,
                    f"✅ *Job Accepted!*\n\n"
                    f"The customer has been notified you're on your way.{eta_note}\n\n"
                    f"🆔 Job ref: *{request_uuid}*\n\n"
                    f"Type *menu* when you need to update the job status."
                )
                set_session(phone, "active")
            else:
                logger.error(f"Provider accept failed {resp.status_code}: {resp.text[:200]}")
                await wa_text(phone, f"⚠️ Could not accept job (server error). Please call dispatch.\nRef: {request_uuid}")
        except Exception as e:
            logger.error(f"Provider accept error: {e}")
            await wa_text(phone, "⚠️ Network error. Please call dispatch directly.")
    else:
        # Declined
        await wa_text(phone,
            f"Understood — job declined.\n\n"
            f"You'll be offered the next available job shortly. Stay ready! 💪"
        )
        reset_session(phone)


async def notify_provider_of_job(provider_phone: str, job: dict) -> None:
    """
    Send a provider_job_flow Flow message to a provider when a new job is assigned.
    Falls back to a simple text message if PROVIDER_FLOW_ID is not yet set.

    Call this from your backend (e.g. after dispatching) or via the /notify-provider endpoint.
    """
    assignment_id = job.get("assignment_id", "")
    request_uuid  = job.get("uuid", "")
    service_label = job.get("service_type_name", "Roadside Assistance")
    location      = job.get("pickup_address", "")
    description   = job.get("issue_description", "No details provided")
    payment_method = job.get("payment_method", "cash")
    vehicle_info  = job.get("vehicle_info", "Not specified")
    posted_at     = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")

    set_session(provider_phone, "flow_provider_pending", {
        "assignment_id": assignment_id,
        "request_uuid": request_uuid,
    })

    if PROVIDER_FLOW_ID:
        await wa_flow(
            provider_phone,
            flow_id=PROVIDER_FLOW_ID,
            flow_cta="View & Respond",
            header="New Job Alert",
            body=f"A new {service_label} job is available near you. Tap to view details and accept.",
            init_screen="JOB_DETAILS",
            flow_data={
                "assignment_id": str(assignment_id),
                "request_uuid":  str(request_uuid),
                "service_label": service_label,
                "location":      location,
                "description":   description,
                "payment_method": payment_method,
                "vehicle_info":  vehicle_info,
                "posted_at":     posted_at,
            },
        )
    else:
        # Fallback text + buttons until PROVIDER_FLOW_ID is configured
        await wa_text(provider_phone,
            f"🚨 *New Job Alert!*\n\n"
            f"🔧 {service_label}\n"
            f"📍 {location}\n"
            f"📝 {description}\n"
            f"🚗 Vehicle: {vehicle_info}\n"
            f"💵 Payment: {payment_method}\n\n"
            f"🆔 Ref: {request_uuid}"
        )
        await wa_interactive_buttons(
            provider_phone,
            body="Do you accept this job?",
            buttons=[("accept_job", "✅ Accept"), ("decline_job", "❌ Decline")],
        )


# ─── WABA Utility Template Messages (outside 24-hour window) ─────────────────
#
# Template messages are the ONLY way to reach users outside the 24-hour
# customer-initiated window. They require pre-approved templates in Meta
# Business Manager with category = UTILITY or MARKETING.
#
# To create the required templates, go to:
#   Meta Business Manager → WhatsApp Manager → Message Templates → Create Template
# Recommended templates for this service:
#   Name: lra_job_offer      Category: UTILITY
#   Name: lra_job_accepted   Category: UTILITY
#   Name: lra_job_declined   Category: UTILITY
#   Name: lra_provider_payout Category: UTILITY
# ─────────────────────────────────────────────────────────────────────────────


async def wa_template_message(
    to: str,
    template_name: str,
    components: list,
    language_code: str = "en",
) -> dict:
    """
    Send a WhatsApp template message.
    Works OUTSIDE the 24-hour messaging window (UTILITY / MARKETING category).

    components example:
      [{"type": "body", "parameters": [{"type": "text", "text": "Tyre Change"}]}]
    """
    return await wa_send(to, {
        "type": "template",
        "template": {
            "name": template_name,
            "language": {"code": language_code},
            "components": components,
        },
    })


async def wa_job_offer_template(
    provider_phone: str,
    assignment_id: str,
    request_uuid: str,
    service_label: str,
    location: str,
    description: str,
    payment_method: str = "cash",
    vehicle_info: str = "",
) -> bool:
    """
    Send a job offer to a provider via WABA UTILITY template.
    This bypasses the 24-hour session restriction.

    Requires an approved template named 'lra_job_offer' with a body like:
      "New job alert! 🚨\n Service: {{1}}\n Location: {{2}}\n Details: {{3}}\n Ref: {{4}}"

    Returns True if the API call succeeded.
    """
    try:
        body_params = [
            {"type": "text", "text": service_label[:512]},
            {"type": "text", "text": location[:512]},
            {"type": "text", "text": (description or "No details")[:512]},
            {"type": "text", "text": str(request_uuid)[:64]},
        ]
        resp = await wa_template_message(
            to=provider_phone,
            template_name="lra_job_offer",
            components=[{"type": "body", "parameters": body_params}],
        )
        wamid = resp.get("messages", [{}])[0].get("id")
        logger.info(
            "Template job offer sent to %s — wamid=%s (assignment=%s)",
            provider_phone, wamid, assignment_id,
        )
        return True
    except Exception as exc:
        logger.warning("Template message failed for %s: %s", provider_phone, exc)
        return False


async def wa_notify_job_accepted_template(
    customer_phone: str,
    provider_name: str,
    eta_minutes: int | None,
    request_uuid: str,
) -> bool:
    """
    Notify the customer that a provider accepted their job request.
    Uses UTILITY template 'lra_job_accepted':
      "Great news! {{1}} has accepted your roadside assistance request.\n ETA: {{2}} minutes.\n Ref: {{3}}"
    """
    try:
        eta_str = str(eta_minutes) if eta_minutes else "TBD"
        await wa_template_message(
            to=customer_phone,
            template_name="lra_job_accepted",
            components=[{"type": "body", "parameters": [
                {"type": "text", "text": provider_name},
                {"type": "text", "text": eta_str},
                {"type": "text", "text": str(request_uuid)[:64]},
            ]}],
        )
        return True
    except Exception as exc:
        logger.warning("lra_job_accepted template failed for %s: %s", customer_phone, exc)
        return False


# ─── Webhook endpoints ────────────────────────────────────────────────────────

@app.get("/webhook")
async def verify_webhook(request: Request):
    """
    Safenet / Meta webhook verification challenge.
    Called once when you register the webhook URL in the Safenet dashboard.
    """
    params = dict(request.query_params)
    hub_mode = params.get("hub.mode")
    hub_verify_token = params.get("hub.verify_token")
    hub_challenge = params.get("hub.challenge", "")

    logger.info(f"Verification: mode={hub_mode}, token_match={hub_verify_token == VERIFY_TOKEN}")

    if hub_mode == "subscribe" and hub_verify_token == VERIFY_TOKEN:
        logger.info("✅ Webhook verified successfully")
        return Response(content=hub_challenge, media_type="text/plain")

    logger.warning(f"❌ Webhook verification FAILED — expected token '{VERIFY_TOKEN}', got '{hub_verify_token}'")
    raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Verification token mismatch")


@app.post("/webhook")
async def receive_webhook(request: Request):
    """
    Receive incoming WhatsApp messages from Safenet / Meta Cloud API.
    Validates signature if APP_SECRET is configured, then processes messages.
    """
    raw_body = await request.body()

    # Optional: validate Meta HMAC-SHA256 signature
    if APP_SECRET:
        sig_header = request.headers.get("x-hub-signature-256", "")
        expected = "sha256=" + hmac.new(
            APP_SECRET.encode(), raw_body, hashlib.sha256
        ).hexdigest()
        if not hmac.compare_digest(sig_header, expected):
            logger.warning("Signature validation failed")
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid signature")

    try:
        body = json.loads(raw_body)
    except json.JSONDecodeError:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid JSON")

    logger.debug(f"Incoming payload: {json.dumps(body)[:500]}")

    # Meta / Safenet Cloud API format
    for entry in body.get("entry", []):
        for change in entry.get("changes", []):
            value = change.get("value", {})

            # Handle delivery/read status updates (no reply needed)
            for s in value.get("statuses", []):
                logger.info(f"Status update: msg_id={s.get('id')} → {s.get('status')}")

            # Handle incoming messages
            for msg in value.get("messages", []):
                phone: str = msg.get("from", "")
                msg_type: str = msg.get("type", "text")
                msg_id: str = msg.get("id", "")

                # Extract text content based on type
                content = ""
                if msg_type == "text":
                    content = msg.get("text", {}).get("body", "")
                elif msg_type == "interactive":
                    interactive = msg.get("interactive", {})
                    reply = interactive.get("button_reply") or interactive.get("list_reply") or {}
                    content = reply.get("id", "") or reply.get("title", "")
                elif msg_type == "location":
                    loc = msg.get("location", {})
                    content = f"GPS:{loc.get('latitude')},{loc.get('longitude')}"

                logger.info(f"📨 from={phone} type={msg_type} content='{content[:80]}'")

                if phone:
                    await handle_message(phone, content, msg_type, msg)

    return {"status": "ok"}


# ── Flow endpoint encryption helpers ─────────────────────────────────────────

def _decrypt_flow_request(body: dict) -> dict:
    """
    Decrypt an incoming encrypted WABA Flow request.
    Meta encrypts all requests with the public key registered via
    POST /{phone_number_id}/whatsapp_business_encryption.

    Body schema: {encrypted_flow_data, encrypted_aes_key, initial_vector}
    Returns decrypted payload dict.
    """
    if not _CRYPTO_AVAILABLE or not _FLOW_PRIVATE_KEY:
        raise HTTPException(status_code=503, detail="Crypto not available — cannot decrypt flow request")

    try:
        encrypted_aes_key  = base64.b64decode(body["encrypted_aes_key"])
        initial_vector     = base64.b64decode(body["initial_vector"])
        encrypted_flow_data = base64.b64decode(body["encrypted_flow_data"])
    except (KeyError, Exception) as e:
        raise HTTPException(status_code=400, detail=f"Bad encrypted flow body: {e}")

    # Decrypt the AES-256 key using our RSA private key (OAEP + SHA-256)
    try:
        aes_key = _FLOW_PRIVATE_KEY.decrypt(
            encrypted_aes_key,
            _asym_padding.OAEP(
                mgf=_asym_padding.MGF1(algorithm=_hashes.SHA256()),
                algorithm=_hashes.SHA256(),
                label=None,
            ),
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"AES key decryption failed: {e}")

    # Decrypt the flow data with AES-256-GCM
    try:
        decrypted_bytes = AESGCM(aes_key).decrypt(initial_vector, encrypted_flow_data, None)
        return json.loads(decrypted_bytes), aes_key, initial_vector
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"AES-GCM decryption failed: {e}")


def _encrypt_flow_response(response_payload: dict, aes_key: bytes, initial_vector: bytes) -> str:
    """
    Encrypt the response payload using AES-256-GCM.
    Meta requires the IV to be bit-flipped (XOR 0xFF) for the response.
    Returns base64-encoded ciphertext.
    """
    flipped_iv = bytes(b ^ 0xFF for b in initial_vector)
    ciphertext = AESGCM(aes_key).encrypt(flipped_iv, json.dumps(response_payload).encode(), None)
    return base64.b64encode(ciphertext).decode()


@app.post("/flow-endpoint")
async def flow_data_exchange(request: Request):
    """
    WhatsApp Flows data exchange endpoint (E2E encrypted).

    Meta encrypts every POST to this URL (including health pings).
    We decrypt, process, then encrypt and return the response.

    Docs: https://developers.facebook.com/docs/whatsapp/flows/reference/flowdataexchangeendpoint
    """
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    # Unencrypted health check used by Meta's pre-registration check
    if body.get("action") == "ping" and "encrypted_flow_data" not in body:
        return {"version": "3.0", "data": {"status": "active"}}

    # All normal requests are encrypted
    decrypted, aes_key, iv = _decrypt_flow_request(body)

    action     = decrypted.get("action", "")
    screen     = decrypted.get("screen", "")
    data       = decrypted.get("data", {})
    flow_token = decrypted.get("flow_token", "")

    logger.info(
        "Flow data exchange: action=%r screen=%r token=%s...",
        action, screen, str(flow_token)[:12]
    )

    # Encrypted ping / health check
    if action == "ping":
        resp_payload = {"version": "3.0", "data": {"status": "active"}}
        return Response(
            content=json.dumps({"response": _encrypt_flow_response(resp_payload, aes_key, iv)}),
            media_type="application/json",
        )

    # INIT — return empty data (our screens are static)
    if action == "INIT":
        resp_payload = {"version": "3.0", "screen": screen or "SERVICE_SELECT", "data": {}}
        return Response(
            content=json.dumps({"response": _encrypt_flow_response(resp_payload, aes_key, iv)}),
            media_type="application/json",
        )

    # Pass data through for any navigate / BACK actions
    resp_payload = {"version": "3.0", "data": data}
    return Response(
        content=json.dumps({"response": _encrypt_flow_response(resp_payload, aes_key, iv)}),
        media_type="application/json",
    )


@app.post("/notify-provider")
async def notify_provider_endpoint(request: Request):
    """
    Internal endpoint: trigger a job notification to a provider.

    Strategy:
      1. Try WABA utility template 'lra_job_offer' (works outside 24-hour window).
      2. Fall back to WABA Flow message (PROVIDER_FLOW_ID).
      3. Fall back to interactive button message.

    Expected JSON body:
    {
        "provider_phone": "+263...",
        "assignment_id":  "123",
        "request_uuid":   "abc-uuid",
        "service_type_name": "Tyre Change",
        "pickup_address": "123 Main St, Harare",
        "issue_description": "Flat tyre on front left",
        "payment_method": "EcoCash",
        "vehicle_info": "White Toyota Vitz 2018",
        "use_template": true      // optional: force template mode
    }
    """
    try:
        job = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    provider_phone = job.get("provider_phone", "")
    if not provider_phone:
        raise HTTPException(status_code=422, detail="provider_phone is required")

    use_template = job.get("use_template", False)

    if use_template:
        # Template path — works outside 24-hour window
        ok = await wa_job_offer_template(
            provider_phone=provider_phone,
            assignment_id=str(job.get("assignment_id", "")),
            request_uuid=str(job.get("request_uuid", "")),
            service_label=job.get("service_type_name", "Roadside Assistance"),
            location=job.get("pickup_address", ""),
            description=job.get("issue_description", ""),
            payment_method=job.get("payment_method", "cash"),
            vehicle_info=job.get("vehicle_info", ""),
        )
        method = "template" if ok else "failed"
    else:
        # Flow / interactive path (within 24-hour window)
        await notify_provider_of_job(provider_phone, job)
        method = "flow" if PROVIDER_FLOW_ID else "interactive"

    return {"status": "sent", "provider_phone": provider_phone, "method": method}


@app.post("/send-template")
async def send_template_endpoint(request: Request):
    """
    Admin endpoint: send any approved WABA template to any phone number.
    Useful for bulk alerts, payout notifications, policy updates, etc.

    Expected JSON body:
    {
        "to": "+263...",
        "template_name": "lra_job_offer",
        "language_code": "en",
        "components": [
            {"type": "body", "parameters": [{"type": "text", "text": "value"}]}
        ]
    }
    """
    try:
        payload = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    to = payload.get("to", "")
    template_name = payload.get("template_name", "")
    if not to or not template_name:
        raise HTTPException(status_code=422, detail="'to' and 'template_name' are required")

    resp = await wa_template_message(
        to=to,
        template_name=template_name,
        components=payload.get("components", []),
        language_code=payload.get("language_code", "en"),
    )
    return {"status": "sent", "to": to, "template": template_name, "response": resp}


# ─── Health + debug ──────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {
        "status": "ok",
        "service": "Lee's Road Assist — WhatsApp Bot",
        "verify_token_set": bool(VERIFY_TOKEN),
        "access_token_set": bool(ACCESS_TOKEN),
        "phone_number_id": PHONE_NUMBER_ID,
        "backend_api": BACKEND_API,
        "active_sessions": len(_sessions),
    }


@app.get("/sessions")
async def list_sessions():
    """Debug: view active conversation sessions (dev only)."""
    return {"sessions": _sessions, "count": len(_sessions)}


@app.delete("/sessions/{phone}")
async def clear_session(phone: str):
    """Debug: reset a specific conversation."""
    _sessions.pop(phone, None)
    return {"status": "cleared", "phone": phone}
